version: 2.1

defaults: &defaults
  docker:
    - image: computesoftware/java-neanderthal:c7fb0781c306c1af91545165411f0535d870cc3c-tools-deps

orbs:
  cache: compute/cache@0.0.3

jobs:
  test:
    <<: *defaults

    steps:
      - checkout
      - run: clojure -J-Xmx3500m -A:test

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test